### ISSUE TITLE
Missing Coffee Table Surface Link

### ISSUE THREAD

**Issue by rctoris** [WPI-RAIL/rail_collada_models#11]
There is no surface link for the coffee table currently.

![untitled](https://cloud.githubusercontent.com/assets/954667/6752946/c8c00e70-cee8-11e4-8a18-f38d14d7530d.png)

@PeterMitrano

**Comment by PeterMitrano** [comment]
Yes, I fixed that a while ago in my copy. I'll get all this update stuff
sorted out tonight. Thanks for letting me know :)
